// Central blog post registry
export const BLOG_POSTS = [
  // FLOW / Focus & Productivity
  {
    slug: "deep-work-remote-environment",
    title: "Deep Work in a Remote Environment: How to Achieve Real Focus",
    description: "Strategies for creating distraction-free focus blocks when your office is your living room.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-03-15",
  },
  {
    slug: "binaural-beats-productivity",
    title: "Binaural Beats and Productivity: What the Science Says",
    description: "How specific audio frequencies can enhance concentration and help you enter flow state faster.",
    category: "Focus",
    color: "violet",
    readTime: "7 min",
    date: "2026-03-10",
  },
  {
    slug: "managing-distractions-work-from-home",
    title: "Managing Distractions When Working From Home",
    description: "Practical techniques to handle interruptions from family, notifications, and your own wandering mind.",
    category: "Focus",
    color: "violet",
    readTime: "9 min",
    date: "2026-02-28",
  },
  {
    slug: "ultradian-rhythms-productivity",
    title: "Ultradian Rhythms: Why Your Body Works in 90-Minute Cycles",
    description: "Understanding your body's natural energy cycles and how to align your work schedule with them.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-02-20",
  },
  {
    slug: "context-switching-hidden-cost",
    title: "The Hidden Cost of Context Switching for Remote Workers",
    description: "Research shows it takes 23 minutes to refocus after an interruption. Here's how to minimize switching.",
    category: "Focus",
    color: "violet",
    readTime: "7 min",
    date: "2026-02-10",
  },
  // FUEL / Nutrition & Fasting
  {
    slug: "blood-sugar-focus-connection",
    title: "Blood Sugar and Focus: How What You Eat Affects How You Think",
    description: "The direct link between your meals, glucose levels, and cognitive performance throughout the workday.",
    category: "Nutrition",
    color: "emerald",
    readTime: "8 min",
    date: "2026-03-12",
  },
  {
    slug: "meal-timing-remote-workers",
    title: "Meal Timing for Remote Workers: When to Eat for Peak Performance",
    description: "Strategic meal timing aligned with your work schedule for sustained energy and better focus.",
    category: "Nutrition",
    color: "emerald",
    readTime: "7 min",
    date: "2026-02-25",
  },
  {
    slug: "caffeine-strategy-productivity",
    title: "The Caffeine Strategy: When and How Much Coffee Actually Helps",
    description: "Using caffeine intentionally instead of habitually for genuine cognitive enhancement.",
    category: "Nutrition",
    color: "emerald",
    readTime: "6 min",
    date: "2026-02-15",
  },
  {
    slug: "hydration-cognitive-performance",
    title: "Hydration and Cognitive Performance: The Overlooked Productivity Tool",
    description: "Even mild dehydration reduces focus by 25%. Here's how to stay properly hydrated while working.",
    category: "Nutrition",
    color: "emerald",
    readTime: "6 min",
    date: "2026-01-30",
  },
  // BODY / Movement & Ergonomics
  {
    slug: "sitting-disease-remote-work",
    title: "Sitting Disease: The Remote Worker's Silent Health Crisis",
    description: "Why prolonged sitting is being called the new smoking, and what you can do about it every hour.",
    category: "Movement",
    color: "orange",
    readTime: "9 min",
    date: "2026-03-08",
  },
  {
    slug: "ergonomic-home-office-setup",
    title: "Setting Up an Ergonomic Home Office on Any Budget",
    description: "From expensive standing desks to free posture hacks — how to protect your body at any price point.",
    category: "Movement",
    color: "orange",
    readTime: "10 min",
    date: "2026-02-22",
  },
  {
    slug: "micro-exercises-desk-workers",
    title: "Micro-Exercises: 2-Minute Movements That Prevent Desk Pain",
    description: "Quick targeted exercises you can do between meetings without changing clothes or breaking a sweat.",
    category: "Movement",
    color: "orange",
    readTime: "7 min",
    date: "2026-02-12",
  },
  {
    slug: "posture-correction-guide",
    title: "Posture Correction for Laptop Users: A Step-by-Step Guide",
    description: "How to identify and fix the most common posture problems caused by working on a laptop all day.",
    category: "Movement",
    color: "orange",
    readTime: "8 min",
    date: "2026-01-28",
  },
  // JOURNAL / Planning & Goals
  {
    slug: "daily-planning-remote-productivity",
    title: "The 5-Minute Daily Plan That Doubles Remote Worker Productivity",
    description: "A simple morning planning ritual that gives structure to your day without rigid scheduling.",
    category: "Planning",
    color: "cyan",
    readTime: "7 min",
    date: "2026-03-05",
  },
  {
    slug: "task-prioritization-methods",
    title: "Task Prioritization for Remote Workers: Beyond the To-Do List",
    description: "Methods for deciding what to work on when everything feels urgent and nobody is telling you what to do.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-02-18",
  },
  {
    slug: "end-of-day-ritual-remote-work",
    title: "The End-of-Day Ritual: How to Actually Stop Working When You Work From Home",
    description: "Creating a clear boundary between work and personal time when your office never closes.",
    category: "Planning",
    color: "cyan",
    readTime: "7 min",
    date: "2026-02-05",
  },
  {
    slug: "preventing-burnout-remote-workers",
    title: "Preventing Burnout as a Remote Worker: Early Signs and Practical Solutions",
    description: "How to recognize burnout before it hits and build sustainable work habits that protect your mental health.",
    category: "Planning",
    color: "cyan",
    readTime: "9 min",
    date: "2026-01-25",
  },
  {
    slug: "work-life-balance-digital-nomads",
    title: "Work-Life Balance for Digital Nomads: Structure Without Rigidity",
    description: "How to create healthy routines that travel with you, no matter which time zone you wake up in.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-01-15",
  },
  // Batch 1 new articles
  {
    slug: "sleep-optimization-remote-workers",
    title: "Sleep Optimization for Remote Workers: Science-Based Tips",
    description: "Improve your sleep quality with evidence-based strategies designed for people who work from home. Better sleep means sharper focus.",
    category: "Focus",
    color: "violet",
    readTime: "9 min",
    date: "2026-04-08",
  },
  {
    slug: "standing-desk-benefits-guide",
    title: "Standing Desk Benefits: Complete Transition Guide 2026",
    description: "Everything you need to know about switching to a standing desk. Benefits, risks, and a practical transition timeline for remote workers.",
    category: "Movement",
    color: "orange",
    readTime: "9 min",
    date: "2026-04-06",
  },
  {
    slug: "digital-detox-after-work",
    title: "Digital Detox After Work: How to Unplug and Recharge",
    description: "Screen-free evening routines that help remote workers decompress, sleep better, and avoid burnout. Practical unplugging strategies.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-04-04",
  },
  {
    slug: "home-office-lighting-productivity",
    title: "Home Office Lighting: How Light Affects Your Productivity",
    description: "Optimize your workspace lighting to reduce eye strain, boost alertness, and improve your circadian rhythm. A practical guide.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-04-02",
  },
  {
    slug: "meal-prep-remote-workers",
    title: "Meal Prep for Remote Workers: Simple Weekly Plans",
    description: "Easy meal prep strategies that save time and fuel your brain. Weekly plans designed for busy remote professionals.",
    category: "Nutrition",
    color: "emerald",
    readTime: "8 min",
    date: "2026-03-30",
  },
  // Batch 2 articles
  {
    slug: "walking-meetings-creativity-boost",
    title: "Walking Meetings: How Movement Boosts Creativity",
    description: "Why walking during calls improves creative thinking by up to 60%. How to make walking meetings work for remote teams.",
    category: "Movement",
    color: "orange",
    readTime: "8 min",
    date: "2026-03-28",
  },
  {
    slug: "remote-work-loneliness-solutions",
    title: "Remote Work Loneliness: How to Stay Connected Solo",
    description: "Practical strategies to combat isolation when working from home. Build meaningful connections without a traditional office.",
    category: "Planning",
    color: "cyan",
    readTime: "9 min",
    date: "2026-03-26",
  },
  {
    slug: "mindfulness-focus-remote-work",
    title: "Mindfulness for Focus: A Remote Worker's Guide 2026",
    description: "Simple mindfulness techniques that sharpen focus and reduce stress. No meditation experience required. Start in 5 minutes.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-03-24",
  },
  {
    slug: "power-naps-productivity-science",
    title: "Power Naps: The Science of Midday Rest for Focus",
    description: "How a 20-minute nap boosts alertness by 54%. The science, optimal timing, and technique of effective power naps for workers.",
    category: "Focus",
    color: "violet",
    readTime: "7 min",
    date: "2026-03-22",
  },
  {
    slug: "brain-fog-causes-solutions",
    title: "Brain Fog at Work: Causes and Quick Solutions",
    description: "Why your brain feels cloudy at 3pm and what to do about it. Identify common triggers and clear the fog fast.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-03-19",
  },
  // SEO Power Articles
  {
    slug: "morning-routine-remote-workers",
    title: "The Perfect Morning Routine for Remote Workers in 2026",
    description: "Build a morning routine that replaces the commute as your transition into productive work mode.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-03-20",
  },
  {
    slug: "remote-work-productivity-tips",
    title: "15 Proven Remote Work Productivity Tips for 2026",
    description: "Battle-tested strategies from experienced remote workers to maximize your output from anywhere.",
    category: "Focus",
    color: "violet",
    readTime: "10 min",
    date: "2026-03-18",
  },
  {
    slug: "focus-music-work-productivity",
    title: "Focus Music for Work: The Science Behind Productivity Soundscapes",
    description: "How binaural beats, lo-fi, and ambient sounds affect your brain and which ones actually boost focus.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-03-14",
  },
  {
    slug: "pomodoro-vs-time-blocking",
    title: "Pomodoro vs Time Blocking: Which Productivity Method Works Better?",
    description: "A detailed comparison of two popular focus techniques and how to choose the right one for your work style.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-03-06",
  },
  {
    slug: "best-apps-remote-workers",
    title: "Best Apps for Remote Workers in 2026: The Essential Toolkit",
    description: "The must-have tools for communication, focus, health, and productivity when working remotely.",
    category: "Planning",
    color: "cyan",
    readTime: "10 min",
    date: "2026-03-02",
  },
  {
    slug: "back-pain-sitting-all-day",
    title: "Back Pain From Sitting All Day? A Remote Worker's Recovery Guide",
    description: "Understanding why desk work destroys your back and a complete plan to fix and prevent the damage.",
    category: "Movement",
    color: "orange",
    readTime: "9 min",
    date: "2026-02-26",
  },
  {
    slug: "intermittent-fasting-beginners",
    title: "Intermittent Fasting for Beginners: A Complete 2026 Guide",
    description: "Everything you need to know to start intermittent fasting safely and sustainably.",
    category: "Nutrition",
    color: "emerald",
    readTime: "9 min",
    date: "2026-02-16",
  },
  {
    slug: "eye-strain-computer-screen",
    title: "Eye Strain From Computer Screens: Prevention and Relief for Remote Workers",
    description: "Protect your vision with proven techniques to reduce digital eye strain during long work sessions.",
    category: "Movement",
    color: "orange",
    readTime: "7 min",
    date: "2026-02-08",
  },
  {
    slug: "stay-motivated-working-from-home",
    title: "How to Stay Motivated Working From Home: A Science-Based Approach",
    description: "Why willpower fails and what actually works to maintain drive and energy as a remote worker.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-01-20",
  },
  // Batch 1 remaining articles
  {
    slug: "vitamin-d-remote-workers",
    title: "Vitamin D and Remote Work: The Indoor Worker's Deficiency Crisis",
    description: "Why remote workers are at high risk for vitamin D deficiency. How it affects energy, mood, and focus, plus practical solutions.",
    category: "Nutrition",
    color: "emerald",
    readTime: "8 min",
    date: "2026-03-16",
  },
  {
    slug: "time-blocking-method-guide",
    title: "Time Blocking Method: The Complete Guide for Remote Workers",
    description: "Master the time blocking method to structure your remote workday. Step-by-step guide with templates and real examples.",
    category: "Planning",
    color: "cyan",
    readTime: "9 min",
    date: "2026-03-13",
  },
  {
    slug: "work-from-home-boundaries",
    title: "Work-From-Home Boundaries: A Practical Framework",
    description: "How to set clear boundaries between work and personal life when your office is your living room. A step-by-step framework.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-03-11",
  },
  {
    slug: "gut-health-brain-focus",
    title: "Gut Health and Brain Focus: The Microbiome-Productivity Connection",
    description: "How your gut bacteria directly influence concentration, mood, and mental clarity. Practical nutrition tips for remote workers.",
    category: "Nutrition",
    color: "emerald",
    readTime: "8 min",
    date: "2026-03-09",
  },
  {
    slug: "home-office-noise-management",
    title: "Home Office Noise Management: Creating Your Ideal Sound Environment",
    description: "How ambient noise affects focus and productivity. Practical soundproofing tips and audio strategies for remote workers.",
    category: "Focus",
    color: "violet",
    readTime: "8 min",
    date: "2026-03-07",
  },
  // Batch 3 articles
  {
    slug: "weekend-recovery-routines",
    title: "Weekend Recovery: How to Recharge for the Work Week",
    description: "Strategic weekend habits that prevent burnout and set you up for a productive Monday. Rest smarter, not longer.",
    category: "Planning",
    color: "cyan",
    readTime: "8 min",
    date: "2026-03-04",
  },
  {
    slug: "wrist-pain-typing-prevention",
    title: "Wrist Pain From Typing: Prevention and Relief Guide",
    description: "Prevent carpal tunnel and repetitive strain with ergonomic adjustments and targeted exercises for desk workers.",
    category: "Movement",
    color: "orange",
    readTime: "8 min",
    date: "2026-03-01",
  },
  {
    slug: "remote-work-anxiety-coping",
    title: "Remote Work Anxiety: Coping Strategies That Work",
    description: "Managing work anxiety without an office support system. Evidence-based techniques for calmer, more focused remote workdays.",
    category: "Planning",
    color: "cyan",
    readTime: "9 min",
    date: "2026-02-27",
  },
  {
    slug: "cold-exposure-productivity",
    title: "Cold Exposure and Productivity: What Research Shows",
    description: "Can cold showers really boost focus and energy? What the latest research says about cold exposure benefits for workers.",
    category: "Focus",
    color: "violet",
    readTime: "7 min",
    date: "2026-02-24",
  },
  {
    slug: "desk-yoga-office-routines",
    title: "Desk Yoga: 10-Minute Routines for Remote Workers",
    description: "Gentle yoga sequences you can do at your desk. Relieve tension, improve posture, and reset your focus in minutes.",
    category: "Movement",
    color: "orange",
    readTime: "8 min",
    date: "2026-02-19",
  },
];
